### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by sakulstra**

### CODE REVIEW

**Comment by Argeare5** [comment]
Improvements and questions to the updated file for updating the cache (this one: https://github.com/bgd-labs/aave-governance-ui-helpers/blob/cleanup/src/cache-update.ts) : 

1. We need to use data helper contracts to get data.
2. Need add voting machine proposal data.
3. It is necessary to overwrite cached data until it is final on the contract side. ( Because what I see now is if the data gets into the cache, it will never be overwritten again, one of example https://github.com/bgd-labs/aave-governance-ui-helpers/blob/cleanup/src/cache-update.ts#L67 )
4. We need to optimize the receipt of payloads, the way it is done now is fundamentally wrong, with the approach as it is now, it is impossible to implement updating the data until they are final, since there will be millions of requests.
- we need to receive data on payloads inside proposals, and at the same time filter payload controllers for uniqueness, this way we can set the correct status for the proposal, and minimize requests for payloads since we will never receive unnecessary ones
- events for payload controllers should be cached separately from payload data

In my opinion the perfect logic should be like this:

1. Initialize needed contracts.
2. We get configs and constants from gov core (to get all timings and voting configs to calculate proposal status)
3. Get data for active proposals.
4. Get voting machine data for active proposals.
5. Combine this data and caching.
6. Mapping this data, and get payloads data for each proposal we need. Caching payloads data.
7. Check proposal status with all data.
8. Caching proposal list data. (minimal data for finished proposal)
9. After all caching events.

I have already done all this except caching all events, please take a look this file, and ask me if something not clear for you: https://github.com/bgd-labs/aave-governance-ui-helpers/blob/cleanup/src/lowdb/populateCache.ts

**Comment by sakulstra** [comment]
1. We don't really need them. As far as i can see we mostly use it for stuff like pagination which is a bit unnecessary for caching as in most cases there will only be 1-2 proposals that are not cached in their final state.
  1.1 I have a rather strong opinion on that, as this way for cli etc we can run agnostic by just passing `--governanceAddress 0xsth`, while with helpers it's becoming complicated. Personally I don't really see the benefit of these helpers anyways @kyzia551 - what is the advantage/if any over doing 4 `getProposalById` via multicall?
  1.2 For caching itself i would say it's even not so optimal, If you have a long proposal followed by a few short(that already finalized) and a few short that aren't finalized you either need to fetch data you don't need, or do multiple calls as well.
3. Fair point on other projects we don't need this, so I didn't include it. Could be easily added to caching as well.
4. I think this comment is wrong. In the file/line you linked exactly the overwriting is happening -> when it's not cached or not final we overwrite/update the cache.
5. I think there's some misunderstanding. Why would there be millions of requests?, what is fundamentally wrong? This is how it's done in all other projects we have -> we fetch payloads from payloadsController and update the cache if it's non final.
  5.1 I don't disagree that there's optimization potential - e.g. currently we always fetch events in a range based on [lastCachedEvent, currentBlock] which usually is nonsense. We could optimize it quite a lot when just caching `lastCachedBlock` somewhere. For now honestly I did not bother. On seatbelt updating the cache and simulating the proposals takes ~1m (in average ~40s updating the cache) ... we run this every 4h so if it's 40s or 5s doesn't really matter at all (for me). Sth one might want to improve, but at the same time probably sth that doesn#t matter here either.

---

All of that said, I think i'd close this pr and keep this whole caching to you guys.
My original intention was to harmonize the caching (especially as when gov v3 went live the caching for mainnet here was completely broken) and then use this package in other projects to have less duplication.

After looking a bit into the code and having all the discussions on slack though, I feel like there are some design decisions taken here I don't feel comfortable with (e.g. the altered/(in my eyes) wrongly enumerated enums) that make it:
a) non trivial to harmonize
b) I feel like the upside of easily understandable code is lost, when things like [this](https://github.com/bgd-labs/aave-governance-ui-helpers/pull/31/files#diff-266cba089ed5319dbc375d38a4c38a0fd57d0a00abc74bb459b5f41fd9db9ab7R42) are no longer easily possible.

**Comment by sakulstra** [comment]
just as i wanted to check the improvement on 4.1 - by simply caching the last seen block the caching time drops to <2s for me.

**Comment by Argeare5** [comment]
hey @sakulstra I tried to combine everything together (yours version and my, about cache), in general, the data format for payloads does not change at all (remains as you had), only for proposals data changes a little (added VM data), but I think it will also suit you (I saved state from contracts, so you can use [this](https://github.com/bgd-labs/aave-governance-ui-helpers/pull/31/files#diff-266cba089ed5319dbc375d38a4c38a0fd57d0a00abc74bb459b5f41fd9db9ab7R42 if need), please take a look when you have time, here is this file to build the cache: https://github.com/bgd-labs/aave-governance-ui-helpers/blob/feat/cache-update/src/scripts/update-cache.ts

**Pull request closed without merging**
